### ISSUE TITLE
Windows integration tests fail running through VS

### ISSUE THREAD

**Issue by jrsurge** [ScintillatorSynth/Scintillator#113]
On Windows, two integration tests fail in VS (building with VS triggers the testing):
* `test_images`
```
15>------ Build started: Project: test_images, Configuration: Release x64 ------
15>configuring sclang to include Scintillator classes.
15>Traceback (most recent call last):
15>  File "C:/Users/jrsurge/Documents/Programming/Scintillator/tools/run-sclang.py", line 47, in <module>
15>    main(sys.argv[1:])
15>  File "C:/Users/jrsurge/Documents/Programming/Scintillator/tools/run-sclang.py", line 12, in main
15>    assert os.path.exists(sclang_path)
15>AssertionError
15>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(230,5): error MSB6006: "cmd.exe" exited with code 1.
15>Done building project "test_images.vcxproj" -- FAILED.
```
* `compare_images`
```
16>------ Build started: Project: compare_images, Configuration: Release x64 ------
16>Traceback (most recent call last):
16>  File "../tools/compare-test-images.py", line 8, in <module>
16>    import yaml
16>ImportError: No module named 'yaml'
16>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(230,5): error MSB6006: "cmd.exe" exited with code 1.
16>Done building project "compare_images.vcxproj" -- FAILED.
```

-------

test_images is being passed the wrong options?
compare_images is failing because of the Python install missing the yaml package.

## Steps

- [ ] Investigate options passing
- [ ] Update Python install
  - [ ] Success
    - [ ] Require min version of Python on Windows
  - [ ] Failure
    - [ ] Install yaml package
      - [ ] Success
        - [ ] Require YAML package on Windows
      - [ ] Failure
        - [ ] Investigate

**Comment by lnihlen** [comment]
Working on this right now. You will also need to install ImageMagick to do the image comparison. It needs the command line tool "compare.exe" which it uses for pixel comparison with reference images, and for generating the diff images that appear in the html report.

**Comment by lnihlen** [comment]
(p.s. I would love to ultimately use Scintillator itself for image comparison)

**Comment by lnihlen** [comment]
Oh, this is specific to Visual Studio. Yeah this stuff wasn't working on the command line, either. So my PR, while relevant, will not fix this issue. Sorry for the spam!

**Comment by lnihlen** [comment]
Also, you will need to have run cmake with `-DSCIN_SCLANG=<path to sclang.exe>`

**Comment by jrsurge** [comment]
not sure these are specific to VS, just mentioned for completeness really.

The first issue will probably be resolved by that cmake flag, but I'll look at the python module thing

**Comment by lnihlen** [comment]
for travis pyyaml install was:
```
git clone https://github.com/yaml/pyyaml/
cd pyyaml
python setup.py install
```

**Comment by lnihlen** [comment]
I'm working on adding windows support to `tools/fetch_sclang.py` which will fetch a limited (no IDE) supercollider build upload to s3 from the ScintillatorSynth/sclang-ext project.
